version: 2

updates:
  - directory: '/'
    labels:
      - 'dependencies'
      - 'github-actions'
    package-ecosystem: 'github-actions'
    schedule:
      day: saturday
      interval: daily
      time: '07:00'
      timezone: Etc/UTC
