#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec syncpack fix-mismatches || exit 1
pnpm exec syncpack set-semver-ranges || exit 1
pnpm exec syncpack format || exit 1

pnpm install
git add package.json pnpm-lock.yaml

pnpm exec ls-lint --config .ls-lint.yaml || exit 1
pnpm exec lint-staged || exit 1
