on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  main:
    env:
      # configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup uv
        # Install a specific uv version using the installer
        run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh
      - name: restore uv cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          path: /tmp/.uv-cache
          restore-keys: |
            ${{ runner.os }}-uv
      - name: run molecule test
        run: |
          uv sync
          source .venv/bin/activate
          molecule test
      - name: minimize uv cache
        run: uv cache prune --ci
