on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: |
            **/pyproject.toml
          enable-cache: true
          ignore-nothing-to-cache: true
          version: 'latest'
      - name: run molecule test
        run: |
          uv sync
          source .venv/bin/activate
          molecule test
