on:
  workflow_call:
    outputs:
      changelog:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.changelog }}
      environment:
        description: 'version'
        value: ${{ jobs.main.outputs.environment }}
      github-pages:
        description: 'whether GitHub Pages is enabled'
        value: ${{ jobs.main.outputs.github-pages }}
      github-pages-path:
        description: 'path of the directory containing the static assets'
        value: ${{ jobs.main.outputs.github-pages-path }}
      latest:
        description: 'is latest'
        value: ${{ jobs.main.outputs.latest }}
      node-version:
        description: 'node.js version'
        value: ${{ jobs.main.outputs.node-version }}
      pnpm-version:
        description: 'pnpm version'
        value: ${{ jobs.main.outputs.pnpm-version }}
      prerelease:
        description: 'is prerelease'
        value: ${{ jobs.main.outputs.prerelease }}
      prerelease-identifier:
        description: 'prerelease identifier'
        value: ${{ jobs.main.outputs.prerelease-identifier }}
      ref:
        description: 'ref'
        value: ${{ jobs.main.outputs.ref }}
      short-commit:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.short-commit }}
      version:
        description: 'version'
        value: ${{ jobs.main.outputs.version }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changelog: ${{ steps.action-context.outputs.changelog }}
      environment: ${{ steps.action-context.outputs.environment }}
      github-pages: ${{ fromJSON(steps.action-context.outputs.github-pages) }}
      github-pages-path: ${{ steps.action-context.outputs.github-pages-path }}
      latest: ${{ fromJSON(steps.action-context.outputs.latest) }}
      node-version: ${{ steps.action-context.outputs.node-version }}
      pnpm-version: ${{ steps.action-context.outputs.pnpm-version }}
      prerelease: ${{ fromJSON(steps.action-context.outputs.prerelease) }}
      prerelease-identifier: ${{ steps.ref.outputs.prerelease-identifier }}
      ref: ${{ steps.ref.outputs.value }}
      short-commit: ${{ steps.action-context.outputs.short-commit }}
      version: ${{ steps.action-context.outputs.version }}
    steps:
      - name: ref
        id: ref
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ steps.ref.outputs.value }}
      - id: action-context
        uses: escapace/action-context@v0.11.0
        with:
          node-version: 22.15.0
          token: ${{ github.token }}
