on:
  workflow_call:
    outputs:
      changelog:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.changelog }}
      commitish:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.commitish }}
      environment:
        description: 'version'
        value: ${{ jobs.main.outputs.environment }}
      latest:
        description: 'is latest'
        value: ${{ jobs.main.outputs.latest }}
      node-version:
        description: 'node.js version'
        value: ${{ jobs.main.outputs.node-version }}
      pnpm-version:
        description: 'pnpm version'
        value: ${{ jobs.main.outputs.pnpm-version }}
      preid:
        description: 'prerelease identifier'
        value: ${{ jobs.main.outputs.preid }}
      prerelease:
        description: 'is prerelease'
        value: ${{ jobs.main.outputs.prerelease }}
      ref:
        description: 'ref'
        value: ${{ jobs.main.outputs.ref }}
      version:
        description: 'version'
        value: ${{ jobs.main.outputs.version }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changelog: ${{ steps.action-context.outputs.changelog }}
      commitish: ${{ steps.action-context.outputs.commitish }}
      environment: ${{ steps.action-context.outputs.environment }}
      latest: ${{ fromJSON(steps.action-context.outputs.latest) }}
      node-version: ${{ steps.action-context.outputs.node-version }}
      pnpm-version: ${{ steps.action-context.outputs.pnpm-version }}
      preid: ${{ steps.ref.outputs.preid }}
      prerelease: ${{ fromJSON(steps.action-context.outputs.prerelease) }}
      ref: ${{ steps.ref.outputs.value }}
      version: ${{ steps.action-context.outputs.version }}
    steps:
      - name: ref
        id: ref
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.ref.outputs.value }}
      - id: action-context
        uses: escapace/action-context@v0.10.9
        with:
          node-version: 22.12.0
          token: ${{ github.token }}
