on:
  workflow_call:
    outputs:
      changelog:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.changelog }}
      commitish:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.commitish }}
      docker-metadata-annotations:
        description: 'docker annotations'
        value: ${{ jobs.main.outputs.docker-metadata-annotations }}
      docker-metadata-json:
        description: 'json output of docker tags and labels'
        value: ${{ jobs.main.outputs.docker-metadata-json }}
      docker-metadata-labels:
        description: 'docker labels'
        value: ${{ jobs.main.outputs.docker-metadata-labels }}
      docker-metadata-tags:
        description: 'docker tags'
        value: ${{ jobs.main.outputs.docker-metadata-tags }}
      environment:
        description: 'version'
        value: ${{ jobs.main.outputs.environment }}
      latest:
        description: 'is latest'
        value: ${{ jobs.main.outputs.latest }}
      node-version:
        description: 'node.js version'
        value: ${{ jobs.main.outputs.node-version }}
      pnpm-version:
        description: 'pnpm version'
        value: ${{ jobs.main.outputs.pnpm-version }}
      prerelease:
        description: 'is prerelease'
        value: ${{ jobs.main.outputs.prerelease }}
      ref:
        description: 'ref'
        value: ${{ jobs.main.outputs.ref }}
      version:
        description: 'version'
        value: ${{ jobs.main.outputs.version }}

jobs:
  main:
    outputs:
      changelog: ${{ steps.action-context.outputs.changelog }}
      commitish: ${{ steps.action-context.outputs.commitish }}
      docker-metadata-annotations: ${{ steps.docker-metadata.outputs.annotations }}
      docker-metadata-json: ${{ steps.docker-metadata.outputs.json }}
      docker-metadata-labels: ${{ steps.docker-metadata.outputs.labels }}
      docker-metadata-tags: ${{ steps.docker-metadata.outputs.tags }}
      environment: ${{ steps.action-context.outputs.environment }}
      latest: ${{ fromJSON(steps.action-context.outputs.latest) }}
      node-version: ${{ steps.node-version.outputs.value }}
      pnpm-version: ${{ steps.pnpm-version.outputs.value }}
      prerelease: ${{ fromJSON(steps.action-context.outputs.prerelease) }}
      ref: ${{ steps.ref.outputs.value }}
      version: ${{ steps.action-context.outputs.version }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: ref
        name: ref
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.ref.outputs.value }}
      - id: action-context
        uses: escapace/action-context@v0.8.0
        with:
          token: ${{ github.token }}
      - env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        id: docker-metadata
        name: docker meta
        uses: docker/metadata-action@v5
        with:
          context: git
          flavor: |
            latest=false
            prefix=
            suffix=
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=match,pattern=v(.*),group=1,value=v${{ steps.action-context.outputs.version }}
            type=match,pattern=v(\d.\d),group=1,enable=${{ startsWith(steps.action-context.outputs.version, '0') == false && fromJSON(steps.action-context.outputs.prerelease) == false }},value=v${{ steps.action-context.outputs.version }}
            type=match,pattern=v(\d),group=1,enable=${{ startsWith(steps.action-context.outputs.version, '0') == false && fromJSON(steps.action-context.outputs.prerelease) == false }},value=v${{ steps.action-context.outputs.version }}
            type=raw,value=latest,enable=${{ fromJSON(steps.action-context.outputs.latest) && fromJSON(steps.action-context.outputs.prerelease) == false }}
      - id: node-version
        name: node-version
        run: |
          echo "value=$(cat package.json | jq -r .engines.node | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)"  >> $GITHUB_OUTPUT
        shell: bash
      - id: pnpm-version
        name: pnpm-version
        run: |
          echo "value=$(cat package.json | jq -r .engines.pnpm | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)" >> $GITHUB_OUTPUT
        shell: bash
