on:
  workflow_call:

permissions:
  contents: read

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: dependency review
        uses: actions/dependency-review-action@v4.9.0
        with:
          # deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0
          fail-on-severity: moderate
