on:
  workflow_call:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dependency review
        uses: actions/dependency-review-action@v4
        with:
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0
          fail-on-severity: moderate
