on:
  workflow_call:
    inputs:
      artifact-name:
        default: package
        required: false
        type: string
      enable-github-packages-npm-registry:
        default: false
        required: false
        type: boolean
      enable-npm-registry:
        default: false
        required: false
        type: boolean
      node-version:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: false

permissions:
  id-token: write
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: download package
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: install latest npm
        run: |
          npm install -g npm
          npm --version
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: inputs.enable-github-packages-npm-registry
        name: publish to github packages npm registry
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
            @escapace:registry=https://npm.pkg.github.com
            always-auth=true
          EOF

          while read -d '' -r file; do
            if [[ "$(tar -axf "${file}" package/package.json -O | jq -r 'if has("private") then .private else true end')" == "false" ]]; then
              npm publish "${file}"
            fi
          done < <(find "." -type f -name '*.tgz' -not -path '**/node_modules/**' -print0 2>/dev/null)
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: inputs.enable-npm-registry
        name: publish to npm registry
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
            @escapace:registry=https://registry.npmjs.org
            always-auth=true
          EOF

          while read -d '' -r file; do
            if [[ "$(tar -axf "${file}" package/package.json -O | jq -r 'if has("private") then .private else true end')" == "false" ]]; then
              npm publish "${file}"
            fi
          done < <(find "." -type f -name '*.tgz' -not -path '**/node_modules/**' -print0 2>/dev/null)
