on:
  workflow_call:
    inputs:
      enable-github-packages-container-registry:
        default: false
        required: false
        type: boolean
      enable-github-packages-npm-registry:
        default: false
        required: false
        type: boolean

permissions:
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    concurrency: retention-policy
    steps:
      - name: name
        id: name
        shell: bash
        run: |
          echo "value=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      - if: inputs.enable-github-packages-container-registry
        uses: actions/delete-package-versions@v5
        with:
          min-versions-to-keep: 10
          package-name: ${{ steps.name.outputs.value }}
          package-type: 'container'
      - if: inputs.enable-github-packages-container-registry
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
          package-name: ${{ steps.name.outputs.value }}
          package-type: 'container'
      - if: inputs.enable-github-packages-npm-registry
        uses: actions/delete-package-versions@v5
        with:
          min-versions-to-keep: 10
          package-name: ${{ steps.name.outputs.value }}
          package-type: 'npm'
