on:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  analysis:
    name: scorecard
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          publish_results: true
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          results_file: results.sarif
          results_format: sarif
          # https://github.com/ossf/scorecard-action#pat-token-creation.
      - name: upload
        uses: github/codeql-action/upload-sarif@v3.27.6
        with:
          sarif_file: results.sarif
